site_name: Bussysteme


site_author: Julian Huber
# Navigation menu
nav:
  - 'Übersicht' : index.md
  - 'Einheit 1 – Einführung GA' : 1_1_Gebäudeautomation.md
  - 'Einheit 2 – Planung & Funktionen' : 1_2_Planungsabläufe.md
  - 'Einheit 3 – Messkette I (Digital)' : 2_1_Messkette.md
  - 'Einheit 4 – Messkette II (Analog)' : 2_1_Messkette_II_Analog.md
  - 'Einheit 5 – Steuerung I (FSM)' : 2_2_Steuerung.md
  - 'Einheit 6 – Steuerung II (OOP)' : 2_2_Steuerung_II_OOP.md
  - 'Einheit 7 – Regelungstechnik I' : 3_1_Blockschaltbild.md
  - 'Einheit 8 – Regelungstechnik II' : 3_2_Regelkreis.md
  - 'Einheit 9 – Regelungstechnik III' : 3_3_Regelverhalten.md
  - 'Einheit 10 – SPS Grundlagen' : 4_1_Speicherprogrammierbare_Steuerung.md
  - 'Einheit 11 – Bussysteme I: Signalisierung' : 5_1_Signalisierung.md
  - 'Einheit 12 – Bussysteme II: Zugriffsverfahren' : 5_2_Buszugriffsverfahren.md
  - 'Einheit 13 – Bussysteme III: Übertragungssicherheit' : 5_3_Uebertragungssicherheit.md
  - 'Einheit 14 – Bussysteme IV: GA-Systeme' : 5_4_Bussysteme_in_der_Gebudeautomation.md
  - 'Optional' :
    - 'IEC 61131-3 Sprachen' : OPTIONAL_4_2_Sprachen_nach_IEC_61131-3.md
    - 'TwinCAT Appendix' : OPTIONAL_4_3_Appendix_Twincat.md
    - 'Smart Metering' : OPTIONAL_6_1_Smart_Metering.md
    - 'Labor' : OPTIONAL_7_1_Labor.md
    - 'Funktionen (alt)' : OPTIONAL_2_3_Funktionen.md
    - 'Objektorientierung (alt)' : OPTIONAL_2_4_Objektorientierung.md
  
theme:
  name: readthedocs

plugins:
  - encryptcontent:
      global_password: mci_!!!

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details

extra_javascript:
  - /javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

dev_addr: '0.0.0.0:7000'